FROM node:22-alpine

RUN mkdir -p /app && chown node:node /app

WORKDIR /app

USER node

COPY --chown=node:node package.json package-lock.json ./

RUN npm ci && mkdir -p /app/.next

EXPOSE 3003

CMD ["npm", "run", "dev"]
